using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("ASWIG Solutions")]
[assembly: AssemblyCopyrightAttribute("Copyright © ASWIG Solutions 2013")]
[assembly: AssemblyFileVersionAttribute("2.0.34")]
[assembly: AssemblyInformationalVersionAttribute("2.0.34.20170704-1428")]

